// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200403170909");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.app.normandy.onsync_skew_sec", 3300);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.isCollectionDismissible", true);
user_pref("app.normandy.user_id", "eb720a67-040d-4df7-9480-dee85a652d33");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1595581105);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1595581081);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1595581225);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1595581135);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1595450605);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 92);
user_pref("browser.newtabpage.activity-stream.impressionId", "{b835c01e-d822-4118-802b-d53a70bcdbf2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1595581127100");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1595582904100");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1595581078865");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1595584678865");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1595581078");
user_pref("browser.slowStartup.averageTime", 4135);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200403170909");
user_pref("browser.startup.homepage_override.mstone", "75.0");
user_pref("browser.startup.lastColdStartupCheck", 1595581077);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1595450609790");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "75.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "8282dafaa72c4b48938f6f0b56d20200");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403170909");
user_pref("extensions.lastAppVersion", "75.0");
user_pref("extensions.lastPlatformVersion", "75.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"ec7b2146-342f-4ed7-b671-edaa138ca063\",\"formautofill@mozilla.org\":\"aa4723ff-b7f5-4c10-acf0-677f4fffdd15\",\"screenshots@mozilla.org\":\"ea62a91d-d227-455e-a823-d8dc8da06952\",\"webcompat-reporter@mozilla.org\":\"52184dde-3ec7-448d-9185-f387ee9c8a3a\",\"webcompat@mozilla.org\":\"952d6964-81eb-4352-9d1d-92f1794de2e1\",\"default-theme@mozilla.org\":\"e9a77d33-2b49-4324-bd19-248a9df01f13\",\"google@search.mozilla.org\":\"b7ea8616-14ff-4095-a777-6f4ec110e2f6\",\"amazondotcom@search.mozilla.org\":\"286dc2b1-d4a7-431e-be77-e23dcf87440d\",\"bing@search.mozilla.org\":\"71bd2816-387f-4aa8-9378-f833939719e0\",\"ddg@search.mozilla.org\":\"db00f9a4-f6ae-444c-8858-e58380746ce7\",\"ebay@search.mozilla.org\":\"5579b3dd-01d8-4f46-8919-6ccd6025340d\",\"twitter@search.mozilla.org\":\"073c623a-f303-48bb-bed2-19cbb6e0a7dc\",\"wikipedia@search.mozilla.org\":\"6471b25e-7664-4069-8e6e-b573335cfe11\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1595581111);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200403170909");
user_pref("media.gmp-manager.lastCheck", 1595581110);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.remote_settings.crlite_filters.checked", 1595581110);
user_pref("security.remote_settings.intermediates.checked", 1595581110);
user_pref("security.sandbox.content.tempDirSuffix", "61cbd35b-9797-4aa2-8c48-d842be993101");
user_pref("security.sandbox.plugin.tempDirSuffix", "55447a23-f99e-449f-89eb-dc17d09aa78c");
user_pref("services.blocklist.addons.checked", 1595581110);
user_pref("services.blocklist.gfx.checked", 1595581110);
user_pref("services.blocklist.pinning.checked", 1595581110);
user_pref("services.blocklist.plugins.checked", 1595581110);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1595549482020\"");
user_pref("services.settings.last_update_seconds", 1595581110);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1595581110);
user_pref("services.settings.main.cfr-fxa.last_check", 1595581110);
user_pref("services.settings.main.cfr.last_check", 1595581110);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1595581110);
user_pref("services.settings.main.hijack-blocklists.last_check", 1595581110);
user_pref("services.settings.main.language-dictionaries.last_check", 1595581110);
user_pref("services.settings.main.message-groups.last_check", 1595581110);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1595581110);
user_pref("services.settings.main.public-suffix-list.last_check", 1595581110);
user_pref("services.settings.main.sites-classification.last_check", 1595581110);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1595581110);
user_pref("services.settings.main.whats-new-panel.last_check", 1595581110);
user_pref("services.settings.security.onecrl.checked", 1595581110);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1595581073);
user_pref("toolkit.telemetry.cachedClientID", "2e09635e-4de6-41a3-899c-e8d64c2d5ad7");
user_pref("toolkit.telemetry.previousBuildID", "20200403170909");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
